name: GRDC_Calib 

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: swat

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build . --tag $IMAGE_NAME
      - name: Run R script
        run: |
          docker run \
            --name test \
            -t ${IMAGE_NAME} \
            Rscript SWATMINT0.2.R -p GW_DELAY:12 -p deiter:2 -p rch:3 -s calib01 -d https://bit.ly/grdcdownload_external_331d632e-deba-44c2-9ed8-396d646adb8d_2021-12-03_19-13_zip
          docker copy test:/root/MINTSWATmodel_output MINTSWATmodel_output/

      - uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: MINTSWATmodel_output/*/*.pdf
      
      - name: Check if the GW_DELAY has been changed
        run: |
          grep -rh GW_DELAY . | awk {'print $1'} | grep 12

          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          IMAGE_ID=${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
